# Generated by jeweler
# DO NOT EDIT THIS FILE
# Instead, edit Jeweler::Tasks in Rakefile, and run `rake gemspec`
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{ruby-plot}
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["David Vorgrimmler", "Martin G\303\274tlein"]
  s.date = %q{2010-02-26}
  s.description = %q{}
  s.email = %q{vorgrimmlerdavid@gmx.de}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "README",
     "Rakefile",
     "VERSION",
     "lib/plot_bars.rb",
     "lib/plot_lines.rb",
     "lib/ruby-plot.rb",
     "lib/ruby-plot.rb"
  ]
  s.has_rdoc = true
  s.homepage = %q{http://github.com/davor/ruby-plot}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.1}
  s.summary = %q{gnuplot wrapper for ruby, especially for plotting roc curves into svg files}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 2

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end
